### PR TITLE
Removing assignment of contributors

### PR DESCRIPTION
**Pull request by nditada**
We want people to be able to start working on things without waiting for a call.

### CODE REVIEW

**Comment by nditada** [comment]
{Agree}

**Comment by nicpottier** [comment]
👍

**Comment by ewheeler** [comment]
👍

**Comment by markboots** [comment]
👍 

Just a note that is helpful for people to create an issue and start a discussion before starting work and blasting a massive PR to review

**Comment by ukanga** [comment]
Agreed

**Pull request merged**
